---
- hosts: all
  become: yes
  pre_tasks:
    - name: 'update apt sources'
      raw: apt-get -y update
    - name: 'install python2'
      raw: apt-get -y install python-simplejson
  vars_files:
    - vars/secrets.yml
    - vars/nodejs.yml
  gather_facts: no
  roles:
    - { role: SimpliField.node }

- hosts: all
  become: yes
  vars_files:
    - vars/secrets.yml
  gather_facts: yes
  pre_tasks:
    # TODO: Remove this pre-task once all the servers are upgraded to datadog 6
    # - name: Remove old datadog apt repo
    #   apt_repository: repo='deb http://apt.datadoghq.com/ stable main' state=absent
  roles:
    - { role: geerlingguy.nginx }
    - { role: development, when: "'development' in group_names" }
    - { role: common }
    - { role: spec, when: "'spec' in group_names" }
