---
- hosts: ec2
  tasks:
    - name: Send notification message via Slack
      run_once: true
      tags: deploy
      local_action:
        module: slack
        domain: "neuranet-dev.slack.com"
        token: "T04PKQH6X/B04QTTJMU/36bVNusqg8qdBCdE6oq1BT43"
        msg: ":rocket: Started deploying everything to {{target}} (page-builder SHA: {{commitHash}})"
        #color: warning
        username: "Ansible"
        icon_url: "http://cdn2.hubspot.net/hub/330046/file-764918166-png/Official_Logos/ansible_circleA_black_small.png?t=1431372330343"
        link_names: 0
        parse: 'none'

- hosts: ec2
  tasks:
    - name: Send notification message via Slack
      run_once: true
      tags: deploy_fast
      local_action:
        module: slack
        domain: "neuranet-dev.slack.com"
        token: "T04PKQH6X/B04QTTJMU/36bVNusqg8qdBCdE6oq1BT43"
        msg: ":rocket: Started fast deploying everything to {{target}} (page-builder Branch: {{branch}} SHA: {{commitHash}})"
        #color: warning
        username: "Ansible"
        icon_url: "http://cdn2.hubspot.net/hub/330046/file-764918166-png/Official_Logos/ansible_circleA_black_small.png?t=1431372330343"
        link_names: 0
        parse: 'none'

- hosts: ec2
  tasks:
    - name: Send notification message via Slack
      run_once: true
      tags: deploy-sites
      local_action:
        module: slack
        domain: "neuranet-dev.slack.com"
        token: "T04PKQH6X/B04QTTJMU/36bVNusqg8qdBCdE6oq1BT43"
        msg: ":rocket: Started deploying flexitive.com and neuranet.com to {{target}}"
        #color: warning
        username: "Ansible"
        icon_url: "http://cdn2.hubspot.net/hub/330046/file-764918166-png/Official_Logos/ansible_circleA_black_small.png?t=1431372330343"
        link_names: 0
        parse: 'none'

- hosts: all
  tasks:
  - name: Create 2 batches of all hosts
    group_by: key=batch-{{batch | default(1)}}
    tags:
      - always

- hosts: batch-1
  max_fail_percentage: 1
#  serial: "50%" # DO NOT CHANGE THIS
  vars_files:
    - vars/secrets.yml
    - vars/nodejs.yml
  pre_tasks:
    - name: Gathering ec2 facts
      action: ec2_facts
      tags:
        - deploy
        - deploy_fast
        - deploy-sites
    - name: Instance De-register (Application LB)
      tags:
        - deploy
        - deploy_fast
      local_action: "shell ~/provisioning/aws/deregister_from_elb.sh {{ ansible_ec2_instance_id }} {{ app_target_group }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
        AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
        AWS_DEFAULT_REGION: "{{aws_region}}"
      when: "'webservers' in group_names"
  roles:
    - { role: common }
    - { role: flexitive-web, when: "'webservers' in group_names" }
    - { role: flexitive-worker, when: "'workers' in group_names" }
    - { role: flexitive-sse, when: "'sseservers' in group_names" }
  post_tasks:
    - name: Instance Register (Application LB)
      tags:
        - deploy
        - deploy_fast
      local_action: "shell ~/provisioning/aws/register_with_elb.sh {{ ansible_ec2_instance_id }} {{ app_target_group }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
        AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
        AWS_DEFAULT_REGION: "{{aws_region}}"
      when: "'webservers' in group_names"
    - name: Run migration
      run_once: true
      sudo: no
      tags:
        - deploy
        - deploy_fast
      command: node_modules/.bin/knex migrate:latest chdir="{{www_dir}}/page-builder{{branch_sub_folder | default()}}"

- hosts: batch-2
  max_fail_percentage: 1
#  serial: "50%" # DO NOT CHANGE THIS
  vars_files:
    - vars/secrets.yml
    - vars/nodejs.yml
  pre_tasks:
    - name: Gathering ec2 facts
      action: ec2_facts
      tags:
        - deploy
        - deploy_fast
        - deploy-sites
    - name: Instance De-register (Application LB)
      tags:
        - deploy
        - deploy_fast
      local_action: "shell ~/provisioning/aws/deregister_from_elb.sh {{ ansible_ec2_instance_id }} {{ app_target_group }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
        AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
        AWS_DEFAULT_REGION: "{{aws_region}}"
      when: "'webservers' in group_names"
  roles:
    - { role: common }
    - { role: flexitive-web, when: "'webservers' in group_names" }
    - { role: flexitive-worker, when: "'workers' in group_names" }
    - { role: flexitive-sse, when: "'sseservers' in group_names" }
  post_tasks:
    - name: Instance Register (Application LB)
      tags:
        - deploy
        - deploy_fast
      local_action: "shell ~/provisioning/aws/register_with_elb.sh {{ ansible_ec2_instance_id }} {{ app_target_group }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
        AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
        AWS_DEFAULT_REGION: "{{aws_region}}"
      when: "'webservers' in group_names"
    - name: Run migration
      run_once: true
      sudo: no
      tags:
        - deploy
        - deploy_fast
      command: node_modules/.bin/knex migrate:latest chdir="{{www_dir}}/page-builder{{branch_sub_folder | default()}}"

- hosts: ec2
  tasks:
  - name: Send notification message via Slack
    run_once: true
    tags: deploy
    local_action:
      module: slack
      domain: "neuranet-dev.slack.com"
      token: "T04PKQH6X/B04QTTJMU/36bVNusqg8qdBCdE6oq1BT43"
      msg: ":star2: Finished deploying everything to {{target}}"
      #color: good
      username: "Ansible"
      icon_url: "http://cdn2.hubspot.net/hub/330046/file-764918166-png/Official_Logos/ansible_circleA_black_small.png?t=1431372330343"
      link_names: 0
      parse: 'none'

- hosts: ec2
  tasks:
  - name: Send notification message via Slack
    run_once: true
    tags: deploy_fast
    local_action:
      module: slack
      domain: "neuranet-dev.slack.com"
      token: "T04PKQH6X/B04QTTJMU/36bVNusqg8qdBCdE6oq1BT43"
      msg: ":star2: Finished fast deploying everything to {{target}}"
      #color: good
      username: "Ansible"
      icon_url: "http://cdn2.hubspot.net/hub/330046/file-764918166-png/Official_Logos/ansible_circleA_black_small.png?t=1431372330343"
      link_names: 0
      parse: 'none'

- hosts: ec2
  tasks:
  - name: Send notification message via Slack
    run_once: true
    tags: deploy-sites
    local_action:
      module: slack
      domain: "neuranet-dev.slack.com"
      token: "T04PKQH6X/B04QTTJMU/36bVNusqg8qdBCdE6oq1BT43"
      msg: ":star2: Finished deploying flexitive.com and neuranet.com to {{target}}"
      #color: good
      username: "Ansible"
      icon_url: "http://cdn2.hubspot.net/hub/330046/file-764918166-png/Official_Logos/ansible_circleA_black_small.png?t=1431372330343"
      link_names: 0
      parse: 'none'
